package com.simshield.protection;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.*;
import android.widget.*;

public class MainActivity extends Activity {
  private SharedPreferences prefs; private TextView score, headline, status, detail, chip; private View riskDot; private SecurityApiClient riskApi;
  private final int BLUE=Color.rgb(49,95,212), GREEN=Color.rgb(18,123,83), RED=Color.rgb(187,35,67);
  @Override public void onCreate(Bundle b){super.onCreate(b); prefs=getSharedPreferences("simshield",MODE_PRIVATE); riskApi=new SecurityApiClient(BuildConfig.RISK_API_BASE_URL); createChannel(); if(android.os.Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED) requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},7); build(); showRisk(false);}
  private void build(){ ScrollView scroll=new ScrollView(this); LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(12),dp(18),dp(30));root.setBackgroundColor(Color.rgb(248,249,255));scroll.addView(root); setContentView(scroll);
    TextView title=text("SIMShield Protection",22,Color.rgb(24,32,51));title.setPadding(0,dp(8),0,dp(16));root.addView(title);
    LinearLayout hero=box(BLUE,22); hero.setOrientation(LinearLayout.VERTICAL); hero.setPadding(dp(20),dp(20),dp(20),dp(20)); headline=text("You’re protected",25,Color.WHITE);hero.addView(headline);TextView sub=text("DEVICE & ACCOUNT PROTECTION",11,Color.rgb(218,229,255));sub.setPadding(0,dp(8),0,0);hero.addView(sub);score=text("18  / 100",43,Color.WHITE);score.setPadding(0,dp(20),0,0);hero.addView(score);root.addView(hero,new LinearLayout.LayoutParams(-1,-2));
    addHeader(root,"PROTECTION STATUS");LinearLayout risk=card();risk.setOrientation(LinearLayout.VERTICAL);LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(16),dp(16),dp(16),dp(12));riskDot=new View(this);riskDot.setLayoutParams(new LinearLayout.LayoutParams(dp(12),dp(12)));row.addView(riskDot);LinearLayout words=new LinearLayout(this);words.setOrientation(LinearLayout.VERTICAL);words.setPadding(dp(14),0,0,0);status=text("No active threat detected",15,Color.rgb(24,32,51));words.addView(status);TextView s=text("Your SIM and protected accounts show normal activity.",12,Color.rgb(101,112,138));words.addView(s);row.addView(words,new LinearLayout.LayoutParams(0,-2,1));chip=text("LOW",11,GREEN);chip.setPadding(dp(9),dp(6),dp(9),dp(6));row.addView(chip);risk.addView(row);detail=text("SIMShield monitors device and mobile-number risk signals. Account alerts are provided only by linked, authorized providers.",12,Color.rgb(88,99,126));detail.setPadding(dp(16),dp(12),dp(16),dp(16));risk.addView(detail);root.addView(risk);
    addHeader(root,"MONITORING");LinearLayout monitor=card();addSwitch(monitor,"SIM change monitoring","Alert when a telecom partner reports a recent SIM lifecycle change","sim");addSwitch(monitor,"Account risk alerts","Receive security signals from linked banks and wallets","account");addSwitch(monitor,"Device security checks","Detect unfamiliar device or sign-in signals","device");root.addView(monitor);
    addHeader(root,"DEVELOPER SIMULATION");LinearLayout actions=card();Button sim=button("Simulate SIM swap",true), esim=button("Simulate eSIM change",true), takeover=button("Simulate full account takeover",true), safe=button("Clear local display",false);actions.setPadding(dp(12),dp(12),dp(12),dp(12));actions.addView(sim);actions.addView(esim);actions.addView(takeover);actions.addView(safe);sim.setOnClickListener(v->simulate("simSwap",true));esim.setOnClickListener(v->simulate("esimChange",true));takeover.setOnClickListener(v->simulate("accountTakeover",true));safe.setOnClickListener(v->{showRisk(false);toast("Display cleared", "This does not resolve any backend alert.");});root.addView(actions);TextView note=text("Simulation only. Real carrier events are received by the backend through authorized telecom partners; this app does not read OTPs, SIM identifiers, or bank passwords.",12,Color.rgb(88,99,126));note.setPadding(0,dp(20),0,0);root.addView(note);
  }
  private void showRisk(boolean high){score.setText(high?"91  / 100":"18  / 100");headline.setText(high?"Action needed":"You’re protected");status.setText(high?"Possible SIM-swap or account-takeover risk":"No active threat detected");chip.setText(high?"HIGH":"LOW");chip.setTextColor(high?RED:GREEN);riskDot.setBackground(round(high?RED:GREEN,99));detail.setText(high?"Avoid password resets and high-value transfers. Use a trusted device and contact your provider through its official support route.":"SIMShield monitors device and mobile-number risk signals. Account alerts are provided only by linked, authorized providers.");}
  private void simulate(String scenario,boolean fallbackHigh){riskApi.simulate("demo-user",scenario,new SecurityApiClient.Callback(){public void success(SecurityApiClient.RiskResult r){showRisk(!"LOW".equals(r.level));score.setText(r.score+"  / 100");status.setText((r.alertTitle.isEmpty()?"Security simulation completed":r.alertTitle)+" · Simulation");if(r.score>=50)notifyUser();}public void failure(String safeMessage){showRisk(fallbackHigh);toast("Simulation mode",safeMessage);if(fallbackHigh)notifyUser();}});}
  private void notifyUser(){Notification.Builder n=new Notification.Builder(this,"risk").setSmallIcon(android.R.drawable.ic_dialog_alert).setContentTitle("SIMShield: high-risk alert").setContentText("Recent SIM change and unusual activity reported. Pause sensitive actions.").setPriority(Notification.PRIORITY_HIGH).setAutoCancel(true);((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(101,n.build());toast("High-risk alert","Sensitive actions should be paused. Open a verified provider app on a trusted device.");}
  private void createChannel(){if(android.os.Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel("risk","Security risk alerts",NotificationManager.IMPORTANCE_HIGH);((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(c);}}
  private void addSwitch(LinearLayout p,String t,String d,String key){LinearLayout r=new LinearLayout(this);r.setPadding(dp(16),dp(12),dp(16),dp(12));r.setGravity(Gravity.CENTER_VERTICAL);LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.addView(text(t,15,Color.rgb(24,32,51)));x.addView(text(d,12,Color.rgb(101,112,138)));r.addView(x,new LinearLayout.LayoutParams(0,-2,1));Switch sw=new Switch(this);sw.setChecked(prefs.getBoolean(key,true));sw.setOnCheckedChangeListener((a,on)->prefs.edit().putBoolean(key,on).apply());r.addView(sw);p.addView(r);}
  private LinearLayout card(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(0,0,0,0);x.setBackground(round(Color.WHITE,18));LinearLayout.LayoutParams l=new LinearLayout.LayoutParams(-1,-2);l.setMargins(0,0,0,dp(4));x.setLayoutParams(l);return x;} private LinearLayout box(int c,int r){LinearLayout x=new LinearLayout(this);x.setBackground(round(c,r));return x;} private TextView text(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);return v;} private Button button(String s,boolean red){Button b=new Button(this);b.setText(s);b.setTextColor(red?RED:BLUE);return b;} private void addHeader(LinearLayout p,String s){TextView h=text(s,12,Color.rgb(101,112,138));h.setPadding(0,dp(20),0,dp(8));p.addView(h);} private GradientDrawable round(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;} private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);} private void toast(String t,String m){Toast.makeText(this,t+"\n"+m,Toast.LENGTH_LONG).show();}
}
